### PR TITLE
Migrate macros to scala 3

### PR DESCRIPTION
**Pull request by jchyb**
This PR is an update of PR #82, migrating macros to Scala 3. Since the main sangria project cannot be used in this project yet, a number of separate unit tests were added. While I would consider the migration to be mostly complete, I have not yet managed to have the main sangria module locally run its tests in Scala 3, so for now I am keeping this PR as a draft in case some errors will be found later. I did manage to have the non-test code compile in the core module though, which is how I discovered and fixed the `MethodTooLarge` exceptions I would get there. I tried to keep the code as as similar to the scala 2 version as was reasonable.

### CODE REVIEW

**Comment by jchyb** [comment]
Ready for review I think. All but one (which looks completely unrelated to macro-visit) of the tests compile and pass in the main sangria project with this branch published locally and used as a dependency. 

I know there is _a lot_ of somewhat unpleasant code to get through here and I hope me putting it all here in one PR will not cause any unnecessary stress (especially considering simultaneous PR in other sangria projects).

**Comment by yanns** [comment]
Could you run `sbt githubWorkflowGenerate` and commit the changes?
https://github.com/sangria-graphql/macro-visit/runs/7025554218?check_suite_focus=true

**Comment by yanns** [comment]
One compilation error:
```
 [error] -- [E008] Not Found Error: /home/runner/work/macro-visit/macro-visit/src/main/scala-3/sangria/visitor/VisitMacro.scala:17:19 
[error] 17 |new VisitMacro.visitCode[T](rootNode, transformations)
[error]    |        ^^^^^^^^^^^^^^^^^^^^
[error]    |     type visitCode is not a member of object sangria.visitor.VisitMacro
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 9 s, completed Jun 23, 2022, 2:41:53 PM
```
https://github.com/sangria-graphql/macro-visit/runs/7025886731?check_suite_focus=true

**Review by yanns — APPROVED** [review]
Awesome contribution!

I like the `VisitorStack` and friends that help having type-safe macros.
They may add some performance overhead (instantiation), but I don't see any other ways.

I'd propose to merge that, to cut a RC release, and to iterate from that.
Does it sound good to you?

**Comment by jchyb** [comment]
Sounds great!

**Pull request merged**
