### PR TITLE
cross-compile to scala 3

### PR DESCRIPTION
**Pull request by yanns**
https://github.com/sangria-graphql/sangria/issues/649

WIP, still a lot to do, but the first minimal tests are green.
If someone wants to join the effort, I add tests covering a small part. Those tests should run on scala 2. And then I implement the scala 3 part.

### CODE REVIEW

**Comment by yanns** [comment]
awesome news!

**Comment by bc-tayvs** [comment]
what do you think about using magnolia for macrosses. It should be easier to use and should works on scala 2 and 3 AFAIK

**Comment by jchyb** [comment]
Just a heads up, the macro-visit reimplementation is basically finished and working [here](https://github.com/sangria-graphql/macro-visit/pull/135), I got all of the tests with it to pass in the main sangria repo (outside of the not yet finished, but independent `sangria-derivation` module), I'll try to cleanup and do all of the necessary PRs (for macro-visit, sangria-marshaling-api, where I had to do some changes, and sangria, for now outside of the `sangria-derivation`) tomorrow.

**Comment by yanns** [comment]
https://github.com/sangria-graphql/macro-visit/pull/135

**Pull request closed without merging**
